
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DialogProvider from "@/providers/modal-provider";
import StoreModal from "@/components/modals/store-modal";
import prismadb from "@/lib/prismadb";
import { Toaster } from "@/components/ui/sonner";
import { ClerkProvider } from "@clerk/nextjs";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // ignore error
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const store = prismadb;

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <DialogProvider>
              <StoreModal />
            </DialogProvider>
            {children}
            <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}